# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SocialSharing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialSharing
  
  #Pods for Facebook
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  #Pods for Twitter
  pod 'TwitterKit'

end
